export const RESTAURANT_TYPES = [
  "Tacos",
  "Pizzas",
  "Birrias",
  "Tlayudas",
  "Hamburguesas",
  "Cafetería",
  "Rosticería",
  "Mariscos",
  "Sushi",
  "Pozolería",
  "Antojitos mexicanos",
  "Alitas",
  "Tortas y sándwiches",
  "Hotdogs",
  "Carnes y BBQ",
  "Panadería y pastelería",
  "Jugos y licuados",
  "Comida corrida",
  "Desayunos y brunch",
  "Ramen y sopas",
  "Marisquería",
  "Cocina italiana",
  "Comida china",
  "Helados y postres",
  "Vegana y vegetariana",
  "Otro",
] as const;

export type RestaurantType = (typeof RESTAURANT_TYPES)[number];
